updates
molgenis/ansible-pipelines pull request #136
Opened 2024-08-02 11:34 UTC by RoanKanninga

2024-08-02 11:46 UTC, pneerincx commented on group_vars/gearshift_cluster/vars.yml
> +    owner: 'umcg-atd-dm',
```suggestion
    owner: 'umcg-muhas-dm',
```

2024-08-02 12:30 UTC, pneerincx commented on group_vars/betabarrel_cluster/vars.yml
> +easybuild_version: '4.9.1'
This has not been deployed on BetaBarrel, which is still running with
```
lua_version: '5.1.4.9'
lmod_version: '8.6.2'
easybuild_version: '4.8.0'
```

2024-08-02 12:32 UTC, pneerincx commented on group_vars/betabarrel_cluster/vars.yml
> +extra_easyconfigs_version: 24.05.1
Latest currently deployed is
```
take-it-easyconfigs-24.03.1
```

2024-08-02 12:53 UTC, pneerincx requested changes

2024-08-02 12:53 UTC, pneerincx commented on group_vars/betabarrel_cluster/vars.yml
> +  - name: NGS_Automated_calculateProjectMd5s_RNA  # Unique ID required to update existing cronjob: do not modify.
Als je er wat achter moet plakken om het uniek te maken, dan zou ik de hele waarde van -p pakken, dus ```NGS_Automated_calculateProjectMd5s_NGS_RNA```
en dan zou ik dat ook voor `NGS_Automated_startPipeline` op dezelfde manier doen, want die heeft ook een -p ...

2024-08-02 12:53 UTC, pneerincx commented on group_vars/betabarrel_cluster/vars.yml
> +  #       moveSequencingData.sh -t tmp05"
Hebben we geen soft partitioning op BetaBarrel?

2024-11-27 12:25 UTC, Gerbenvandervries approved these changes

2024-11-27 12:26 UTC, merged