Ansible pipelines deployed on wh-chaperone
molgenis/ansible-pipelines pull request #71
Opened 2022-07-04 14:56 UTC by scimerman

- version updated from 4.5.1 to 4.5.5, as the version 4.5.1 had issues on wh-chaperone having missing `easybuild.main` file after installation (bug)
- the `PYTHONPATH` was incorrectly defined to
`/apps/software//EasyBuild/4.5.5/lib64/python3.6/site-packages/pip`
instead of
`/apps/software/EasyBuild/4.5.5/lib/python3.6/site-packages`

2022-07-11 11:10 UTC, pneerincx commented on roles/install_easybuild/tasks/install_easybuild_with_pip.yml
> +  changed_when: true
If I understand correctly this replaces the `'Get install suffix from pip -V'` task, which can be deleted, right?

2022-07-11 11:11 UTC, pneerincx commented on roles/install_easybuild/tasks/install_easybuild_with_pip.yml
> +- name: 'Determine site-packages location for Lua module file to be correctly configured'
```suggestion
- name: 'Determine site-packages location for Lua module file.'
```

2022-07-11 11:12 UTC, pneerincx requested changes
See inline comments.

2022-07-11 12:04 UTC, scimerman commented on roles/install_easybuild/tasks/install_easybuild_with_pip.yml
> +  changed_when: true
Good catch, but no.
This determine the PYTHONPATH that is works with `lib` and `lib64` pathing and similar change in structure (happened on one of the test system). 
The `pip` executable can be (and **is** on chaperone when you deploy `ansible-pipelines` from user's home folder) pointing to the user's virtual path.
Note that the `pip_path` variable is used only during the installation, and **not** anymore after that. When user runs the code, the executables are used from system and `PYTHONPATH` only.
What was already in current implementation is still valid. New block of code merely adds the script that detects the correct `PYTHONPATH` - > where all the packages ended up being installed.

2022-07-15 15:15 UTC, pneerincx commented on roles/install_easybuild/tasks/install_easybuild_with_pip.yml
> +  changed_when: true
I still do not get it. The only thing the `Get install suffix from pip -V` task did was registering the `python_install_suffix` Ansible variable, which was only used to compile PYTHONPATH. This `python_install_suffix` variable is no longer used anywhere with this commit and PYTHONPATH is more reliably determined using the new `Determine site-packages location for Lua module file to be correctly configured` task. So why do we need to keep the `Get install suffix from pip -V` task?

2022-07-18 08:14 UTC, scimerman commented on roles/install_easybuild/tasks/install_easybuild_with_pip.yml
> +  changed_when: true
You are correct. I checked again, and variable that was used in the templates is not being needed anymore. I removed the part with obsolete code.

2022-07-18 10:23 UTC, pneerincx approved these changes

2022-07-18 10:23 UTC, merged